name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '3.8.5'

      - name: Clean workspace
        run: git clean -fdx

      - name: Compile with Maven
        run: mvn clean compile

      - name: Test with Maven
        run: mvn test

      - name: Build Docker image
        run: |
          docker build -t petclinic1 .
          docker tag petshop  limkel/petshop:3.0
          docker push limkel/petshop:3.0
      - name: Run Trivy
        run: |
          docker run --rm \
            -v ${{ runner.workspace }}:/src \
            aquasec/trivy:latest \
            image limkel/petshop:3.0 > trivy.txt
