name: Maven Build and Deploy

on:
  push:
    branches:
      - start

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update and upgrade APT packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
      - name: Install Maven
        run: |
          sudo apt-get install -y maven
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
