name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clean workspace
        run: git clean -fdx

      - name: Build Docker image
        run: docker build -t iscanprint/tomcat:2.0 -f Dockerfile1 .

      - name: Push Docker image to Docker Hub
        run: docker push iscanprint/tomcat:2.0

      - name: Run Docker container
        run: docker run --rm -d -p 8080:8080 iscanprint/tomcat:2.0
