name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update and upgrade APT packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t iscanprint/petshop:1.1 -f Dockerfile1 .

      - name: Push Docker Image
        run: |
          docker push iscanprint/petshop:1.1
